"""empty message

Revision ID: 43a4d91b576c
Revises: 9651f02ff052
Create Date: 2022-08-15 03:20:14.581219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a4d91b576c'
down_revision = '9651f02ff052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_on')
    op.drop_column('employees', 'deleted_on')
    # ### end Alembic commands ###
